#!/bin/bash
APP="$1"; IMAGE="dokku/$APP"


read -d '' exec_runner <<'EOF'
#!/bin/bash

set -e
app_dir=/app
export HOME=$app_dir
cd \$HOME

for file in .profile.d/*; do source \$file; done
hash -r
"\$@"
EOF

read -d '' start_runner <<'EOF'
#!/bin/bash

set -e
app_dir=/app
user_name=$(grep -o '^u[0-9]\\{4,5\\}' /etc/passwd)
: ${user_name:="www-data"}

export HOME=$app_dir
chown -R $user_name:$user_name $app_dir

hash -r
cd \$HOME

cat << CONF > supervisord.conf
[supervisord]
loglevel=debug
nodaemon=true
CONF

while read line || [ -n "\$line" ]
do
  if [[ "\$line" =~ ^([A-Za-z0-9_-]+):\s*(.+)$ ]]
  then
    name=\${line%%:*}
    command=\${line#*: }
    cat << CONF >> supervisord.conf
[program:\${name}]
command=/exec sh -c "\${command}"
autostart=true
autorestart=true
stopsignal=QUIT

CONF
  fi
done < "Procfile"

cat << CONF >> supervisord.conf
[unix_http_server]
file=/tmp/supervisor.sock
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

CONF


setuidgid $user_name supervisord -c supervisord.conf
EOF

set -e

# Check for Procfile
ID=$(docker run -d $IMAGE test -f app/Procfile)
if [ $(docker wait $ID) -ne 0 ]; then
  exit 0
fi

echo "-----> Preparing Supervisor ..."

CMD="rm /exec && \
  dpkg -s supervisor > /dev/null 2>&1 || \
  (apt-get update && apt-get install -y supervisor && rm -rf /var/lib/apt/lists/*)"

ID=$(docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null

echo "-----> Injecting Supervisor ..."

CMD="cat > /exec && \
  chmod +x /exec"

ID=$(echo "$exec_runner" | docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null

CMD="cat > /start && \
  chmod +x /start"

ID=$(echo "$start_runner" | docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
