#!/bin/bash
APP="$1"; IMAGE="app/$APP"

read -d '' runner <<'EOF'
#!/bin/bash

set -e
export HOME=/app
hash -r
cd \$HOME

cat << CONF > supervisord.conf
[supervisord]
loglevel=debug
nodaemon=true
CONF

while read line || [ -n "\$line" ]; do
  name=\${line%%:*}
  command=\${line#*: }
  cat << CONF >> supervisord.conf
[program:\${name}]
command=/exec sh -c "\${command}"
autostart=true
autorestart=true
stopsignal=QUIT

CONF

done < "Procfile"



supervisord -c supervisord.conf
EOF

set -e

# Check for Procfile
ID=$(docker run -d $IMAGE test -f app/Procfile)
if [ $(docker wait $ID) -ne 0 ]; then
  exit 0
fi

echo "-----> Injecting Supervisor ..."

CMD="cat > /start && \
  dpkg -s supervisor > /dev/null 2>&1 || \
  (apt-get update && apt-get install -y supervisor && apt-get clean)"

ID=$(echo "$runner" | docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
